### ISSUE TITLE
Functionality parity with original game

### ISSUE THREAD

**Issue by Ferrisx4** [esmane/endless-bento#11]
While playing your version of bento, I noticed some differences between the way the original Nancy Drew version and yours functions. For instance, automatically selecting the next shape and/or color is a bit disorienting, and not being able to place a shape without a color (or vice versa) is a bit limiting.

I've made a fork and have at least these two things working more similarly to the original. If you're open to these changes, assign me and I'll make a PR, thanks!

---

Since this is my first issue on this repo I want to say thanks very much for creating this game online! My partner and I recently played through this Nancy Drew game and whenever we got frustrated, or at random other times let's be honest, we'd just go play some bento. Now we can play bento without having to load up Nancy Drew and deal with Yumi.

**Comment by esmane** [comment]
Hey, this is cool! I was playing around with your version for a bit and I like being able to set only the color or the shape of a tile. I didn't look at the code too thoroughly but anyway here are my suggestions:

- Autoselecting should still be an option if the player prefers it for whatever reason. Since the very first release of "endless bento" you have been able to toggle this feature on and off. Autoselection should only happen when the player has it turned on and both a color and a shape are selected.
- Setting just the shape or color of a tile should not overwrite what is already in that tile, unless the tile is already set to whatever it would become (does this make sense?!). For example, suppose you have just the color red selected with no shape. Clicking an empty tile should create a red square (no shape), clicking a triangle with no color should create a red triangle, clicking a yellow diamond should create a red diamond, but clicking a red triangle should create a red tile with no shape. Maybe in practice this wouldn't feel right but it seems intuitive to me.
- Having nothing selected functions the same as having the 'x' selected. Deselecting both the color and the shape should either automatically select the 'x' (not intuitive to me but matches the current behavior), make it so that left-clicking the grid does absolutely nothing (makes sense but is kind of stupid), or be impossible (Probably the best option since I can't think of any reason the player would ever actually want to have no shape or color selected).

What do you think? This is what came to my mind when I was playing your version. I would assume that your control system would be preferred over mine by most people, but I have no idea how many people play my game. Anyways, thanks for the fork!

**Comment by Ferrisx4** [comment]
Hi, it's been a while, I've been pretty busy. I was about to start trying to get this working again but I see that you implemented it yourself (yay)! Thanks a million again for making this.
